/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ParaQuemERouteImport } from './routes/para-quem-e'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SolucoesRouteImport } from './routes/solucoes'
import { Route as ArtigosIndexRouteImport } from './routes/artigos/index'
import { Route as ArtigosSlugRouteImport } from './routes/artigos/$slug'
import { Route as PostSlugRouteImport } from './routes/post/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaQuemERoute = ParaQuemERouteImport.update({
  id: '/para-quem-e',
  path: '/para-quem-e',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesRoute = SolucoesRouteImport.update({
  id: '/solucoes',
  path: '/solucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigosIndexRoute = ArtigosIndexRouteImport.update({
  id: '/artigos/',
  path: '/artigos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigosSlugRoute = ArtigosSlugRouteImport.update({
  id: '/artigos/$slug',
  path: '/artigos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PostSlugRoute = PostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/para-quem-e': typeof ParaQuemERoute
  '/sobre': typeof SobreRoute
  '/solucoes': typeof SolucoesRoute
  '/artigos/$slug': typeof ArtigosSlugRoute
  '/post/$slug': typeof PostSlugRoute
  '/artigos/': typeof ArtigosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/para-quem-e': typeof ParaQuemERoute
  '/sobre': typeof SobreRoute
  '/solucoes': typeof SolucoesRoute
  '/artigos/$slug': typeof ArtigosSlugRoute
  '/post/$slug': typeof PostSlugRoute
  '/artigos': typeof ArtigosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/para-quem-e': typeof ParaQuemERoute
  '/sobre': typeof SobreRoute
  '/solucoes': typeof SolucoesRoute
  '/artigos/$slug': typeof ArtigosSlugRoute
  '/post/$slug': typeof PostSlugRoute
  '/artigos/': typeof ArtigosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/contato'
    | '/para-quem-e'
    | '/sobre'
    | '/solucoes'
    | '/artigos/$slug'
    | '/post/$slug'
    | '/artigos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/contato'
    | '/para-quem-e'
    | '/sobre'
    | '/solucoes'
    | '/artigos/$slug'
    | '/post/$slug'
    | '/artigos'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/contato'
    | '/para-quem-e'
    | '/sobre'
    | '/solucoes'
    | '/artigos/$slug'
    | '/post/$slug'
    | '/artigos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  ContatoRoute: typeof ContatoRoute
  ParaQuemERoute: typeof ParaQuemERoute
  SobreRoute: typeof SobreRoute
  SolucoesRoute: typeof SolucoesRoute
  ArtigosSlugRoute: typeof ArtigosSlugRoute
  PostSlugRoute: typeof PostSlugRoute
  ArtigosIndexRoute: typeof ArtigosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-quem-e': {
      id: '/para-quem-e'
      path: '/para-quem-e'
      fullPath: '/para-quem-e'
      preLoaderRoute: typeof ParaQuemERouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes': {
      id: '/solucoes'
      path: '/solucoes'
      fullPath: '/solucoes'
      preLoaderRoute: typeof SolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigos/': {
      id: '/artigos/'
      path: '/artigos'
      fullPath: '/artigos/'
      preLoaderRoute: typeof ArtigosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigos/$slug': {
      id: '/artigos/$slug'
      path: '/artigos/$slug'
      fullPath: '/artigos/$slug'
      preLoaderRoute: typeof ArtigosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$slug': {
      id: '/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof PostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  ContatoRoute: ContatoRoute,
  ParaQuemERoute: ParaQuemERoute,
  SobreRoute: SobreRoute,
  SolucoesRoute: SolucoesRoute,
  ArtigosSlugRoute: ArtigosSlugRoute,
  PostSlugRoute: PostSlugRoute,
  ArtigosIndexRoute: ArtigosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
